from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_TOOL_WORKSPACE = PROJECT_ROOT / "agent_write"
MEMORY_ROOT = PROJECT_ROOT / "memory"
AGENT_DATA_ROOT = PROJECT_ROOT / ".agent_data"
SESSION_DB_PATH = AGENT_DATA_ROOT / "sessions.sqlite3"
DASHSCOPE_COMPATIBLE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_MAIN_MODEL = "qwen3.5-flash-2026-02-23"
DEFAULT_SUB_AGENT_MODEL = "MiniMax-M2.5"

CONTEXT_WINDOW_TOKENS = 120_000
OUTPUT_TOKEN_RESERVE = 20_000
CONTEXT_EFFECTIVE_LIMIT = CONTEXT_WINDOW_TOKENS - OUTPUT_TOKEN_RESERVE
CONTEXT_BLOCKING_MARGIN = 3_000
CONTEXT_WARNING_MARGIN = 20_000
AUTO_COMPACT_THRESHOLD_RATIO = 0.93
COLLAPSE_COMMIT_RATIO = 0.90
COLLAPSE_BLOCK_SPAWN_RATIO = 0.95
MICRO_COMPACT_IDLE_SECONDS = 300
MICRO_COMPACT_KEEP_RECENT = 2
